### PR TITLE
One sentence per line, for cleaner diffs

### PR DESCRIPTION
**Pull request by davelab6**
:)

### CODE REVIEW

**Comment by frankrolf** [comment]
Markdown is not only parsed, but also supposed to be readable in its raw source format.
I think readability would suffer when breaking the line after each sentence, therefore I won’t merge this.

**Comment by frankrolf** [comment]
This text is supposed to be parsed on a web site, one sentence per line decreases readability.
Therefore: no.

**Comment by davelab6** [comment]
The markdown processor will not separate each line in the HTML on the website.

**Comment by davelab6** [comment]
This makes zero visible changes, but it makes maintaining the file easier for you :)

**Comment by frankrolf** [comment]
Not yet sure how the markdown will be processed, I will consider merging this at a later point.

**Comment by davelab6** [comment]
Markdown doesn't do `<br>`-style linebreaks, so any processing of the file from raw markdown will make the lines appear as paragraphs. You can see this in the github markdown 'rich' diff, which only shows the 2 content changes I made, to remove a `;` and put a file extension in code quotes :)

https://github.com/frankrolf/git-for-type-designers/pull/2/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Pull request closed without merging**
